# Generated by Django 4.1.2 on 2022-10-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='descripcion',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
